# Generated by Django 2.0.1 on 2018-06-17 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='提交日期')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('studentid', models.CharField(max_length=12, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.BooleanField(default=True, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('way', models.BooleanField(default=True, verbose_name='预约批次')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
